### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by youlang1** [hualuoo/attendance_system#1]
您好我想问一下，这个系统我跑的时候在控制台点击链接http://127.0.0.1:8000/跳出的是Django REST框架界面，
![P3NU4D WFARBM KGE您好我想问一下，这个系统我跑的时候在控制台点击链接http://127.0.0.1:8000/跳出的是Django REST框架界面，
%GM5](https://user-images.githubusercontent.com/65811677/82728977-84c45980-9d26-11ea-927c-fc1136adf316.png)
这是因为什么，该怎么改？？急急急

**Comment by hualuoo** [comment]
该项目为前后端分离，Django只用于写API，前端在另一个目录

**Comment by youlang1** [comment]
您好，可以分享一下前端代码嘛，或者说是告知我该怎么做，因为我现在急需这个人脸识别技术的门禁部分，拜托了！
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"華落"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月23日(星期六) 晚上8:52
 收件人:&nbsp;"hualuoo/dormitory_menage_system"<dormitory_menage_system@noreply.github.com&gt;;
 抄送:&nbsp;"ㅤ"<2216879017@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [hualuoo/dormitory_menage_system] 您好 (#1)

 

 

 
该项目为前后端分离，Django只用于写API，前端在另一个目录

**Comment by youlang1** [comment]
您好，您这个源码文件是有前端代码的呀，请问该如何操作能够使浏览器正常运行项目而不加载djanjo rest框架界面呢？！！
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"華落"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月23日(星期六) 晚上8:52
 收件人:&nbsp;"hualuoo/dormitory_menage_system"<dormitory_menage_system@noreply.github.com&gt;;
 抄送:&nbsp;"ㅤ"<2216879017@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [hualuoo/dormitory_menage_system] 您好 (#1)

 

 

 
该项目为前后端分离，Django只用于写API，前端在另一个目录

**Comment by hualuoo** [comment]
前端需要换个端口额外搭建个Web服务器访问，然后批量替换API链接
